# Generated by Django 5.0.6 on 2025-05-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_data', models.JSONField()),
                ('suggested_outfit', models.JSONField()),
                ('user_gender_at_feedback', models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Non-binary', 'Non-binary')], max_length=20, null=True)),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_feedbacks', to='user.userprofile')),
            ],
            options={
                'verbose_name': 'Outfit Feedback',
                'verbose_name_plural': 'Outfit Feedbacks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
