# Generated by Django 5.0.6 on 2025-06-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('preference_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, verbose_name='Preference Type')),
                ('context_temperature_category', models.CharField(blank=True, choices=[('cold_below_10c', 'Cold (Below 10°C)'), ('mild_10_20c', 'Mild (10-20°C)'), ('warm_20_30c', 'Warm (20-30°C)'), ('hot_above_30c', 'Hot (Above 30°C)')], max_length=50, null=True, verbose_name='Temperature Context')),
                ('context_alert_event', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alert Context')),
                ('feedback_source', models.CharField(choices=[('direct_feedback', 'Direct Feedback'), ('manual_entry', 'Manual Entry'), ('inferred', 'Inferred')], default='direct_feedback', max_length=20, verbose_name='Feedback Source')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Preference Count/Strength')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Item Preference',
                'verbose_name_plural': 'User Item Preferences',
                'ordering': ['-updated_at', 'user', 'item_name'],
            },
        ),
    ]
