# Generated by Django 5.0.6 on 2025-05-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_preferred_temperature_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Non-binary', 'Non-binary')], max_length=20, null=True),
        ),
    ]
