# Generated by Django 5.0.6 on 2025-06-11 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('he', 'Hebrew'), ('it', 'Italian'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('sv', 'Swedish'), ('ud', 'Urdu'), ('zh', 'Chinese')], default='en', help_text="User's preferred language for news articles.", max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
